import Link from 'next/link';
import { ArrowRight, Beaker, BookOpen, CircleAlert, FlaskConical, ShieldCheck } from 'lucide-react';
import { EvidenceLadder, MoleculeField } from '@/components/KnowledgeVisuals';
import { KNOWLEDGE_SOURCES } from '@/lib/data/knowledgeSources';

export const metadata = {
  title: 'Cannabis Science | Efifya',
  description: 'Cannabis chemistry, the endocannabinoid system, therapeutic research and the science of whole-plant interactions.',
};

const concepts = [
  { name: 'THC', type: 'Cannabinoid', known: 'THC is psychoactive and can shape perception, mood, appetite, memory and symptom experience. Effects may be sought, therapeutic, neutral or uncomfortable depending on the person and context.', uncertain: 'THC percentage alone does not describe dose, the complete chemical profile or an individual response.', lesson: '/edu/courses/chemistry-and-the-body/cannabinoids-and-the-ecs' },
  { name: 'CBD', type: 'Cannabinoid', known: 'CBD is pharmacologically active without usually producing the same THC-like psychoactive experience. Defined CBD medicines have strong evidence for some narrow indications.', uncertain: 'Retail and artisanal products can differ from studied medicines in formulation, dose and testing.', lesson: '/edu/courses/safety-and-health/medical-evidence' },
  { name: 'Terpenes', type: 'Volatile compounds', known: 'Terpenes shape aroma, plant ecology and potentially parts of human response. Controlled human work shows that d-limonene can modify a specific acute THC effect.', uncertain: 'Aroma only describes part of a cultivar; it does not guarantee energising, relaxing or therapeutic effects by itself.', lesson: '/edu/courses/chemistry-and-the-body/terpenes-flavonoids-and-entourage' },
  { name: 'Entourage effect', type: 'Compound interactions', known: 'Cannabinoids and other constituents can interact through receptors, metabolism and whole-system responses. Some combinations have direct human evidence.', uncertain: 'Which combinations matter clinically—and for whom—remains a product-, ratio-, route- and outcome-specific research question.', lesson: '/edu/courses/chemistry-and-the-body/terpenes-flavonoids-and-entourage' },
];

const reviewedScience = KNOWLEDGE_SOURCES.filter((source) => source.quality === 'peer reviewed' || source.quality === 'authoritative guidance').slice(0, 6);

export default function SciencePage() {
  return <main className="page-shell">
    <header className="relative overflow-hidden rounded-[2rem] border border-brand-primary/10 bg-[radial-gradient(circle_at_78%_18%,rgba(214,168,75,.14),transparent_30%),linear-gradient(145deg,#14241c,#0c1913)] px-6 py-12 sm:px-10 lg:px-14 lg:py-16">
      <div className="relative z-10 max-w-3xl"><p className="clinical-label flex items-center gap-2 text-brand-secondary"><FlaskConical size={14}/> Cannabis science</p><h1 className="newsreader-display mt-5 text-5xl leading-[.94] sm:text-7xl">Explore the chemistry.<br/><span className="text-brand-secondary">Understand the ensemble.</span></h1><p className="mt-7 max-w-2xl text-base leading-7 text-brand-primary/60 sm:text-lg">Learn how cannabinoids, terpenes, flavonoids, dose, route, the ECS and lived context come together to shape experience and therapeutic potential.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/edu/courses/chemistry-and-the-body" className="inline-flex items-center gap-2 rounded-xl bg-brand-secondary px-5 py-3 text-sm font-bold text-brand-stone-50">Begin the chemistry course <ArrowRight size={15}/></Link><Link href="/docs" className="inline-flex items-center gap-2 rounded-xl border border-brand-primary/15 px-5 py-3 text-sm font-bold">Inspect the evidence <BookOpen size={15}/></Link></div></div>
      <MoleculeField className="pointer-events-none absolute bottom-0 right-0 w-[55%] text-brand-secondary opacity-30"/>
    </header>

    <section className="mt-20 grid gap-4 lg:grid-cols-[1.05fr_.95fr]" aria-labelledby="mechanism-heading"><article className="rounded-2xl border border-brand-primary/10 bg-brand-stone-100 p-7 sm:p-10"><p className="clinical-label text-brand-emerald-900">From mechanism to lived outcome</p><h2 id="mechanism-heading" className="newsreader-display mt-4 text-4xl">Mechanism, experience and clinical research answer different questions.</h2><p className="mt-5 text-sm leading-7 text-brand-primary/55">Laboratory work explains plausible pathways. People reveal which changes matter in real life. Controlled human research estimates what defined products tend to do. Efifya keeps all three in the evidence picture.</p><EvidenceLadder className="mt-9 max-w-xl text-brand-emerald-900"/></article><article className="rounded-2xl border border-brand-secondary/20 bg-brand-secondary/[.04] p-7 sm:p-10"><CircleAlert className="text-brand-secondary"/><p className="clinical-label mt-8 text-brand-secondary">Individual response</p><h2 className="newsreader-display mt-3 text-3xl">No universal experience from one number</h2><p className="mt-4 text-sm leading-7 text-brand-primary/55">Dose, route, ratio, the wider chemical profile, metabolism, prior experience and setting all matter. Personal tracking and cannabis-informed clinical or pharmacy support can make medication questions more useful.</p><Link href="/edu/courses/chemistry-and-the-body/dose-route-and-duration" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-brand-secondary">Learn why dose and route vary <ArrowRight size={14}/></Link></article></section>

    <section className="mt-24" aria-labelledby="concepts-heading"><div className="mb-8"><p className="clinical-label text-brand-secondary">Compound explorer</p><h2 id="concepts-heading" className="newsreader-display mt-3 text-4xl sm:text-5xl">What the evidence supports—and what comes next</h2></div><div className="grid gap-4 md:grid-cols-2">{concepts.map((concept)=><article key={concept.name} className="rounded-2xl border border-brand-primary/10 bg-brand-stone-100 p-6"><div className="flex items-center justify-between"><span className="rounded-full border border-brand-primary/10 px-3 py-1 text-[9px] font-bold uppercase tracking-wider text-brand-primary/40">{concept.type}</span><Beaker size={18} className="text-brand-secondary"/></div><h3 className="newsreader-display mt-7 text-4xl">{concept.name}</h3><div className="mt-5 space-y-4"><div className="rounded-xl border border-brand-emerald-900/15 bg-brand-emerald-900/[.04] p-4"><p className="text-[9px] font-bold uppercase tracking-wider text-brand-emerald-900">What evidence supports</p><p className="mt-2 text-sm leading-6 text-brand-primary/60">{concept.known}</p></div><div className="rounded-xl border border-brand-primary/10 p-4"><p className="text-[9px] font-bold uppercase tracking-wider text-brand-primary/35">Open research question</p><p className="mt-2 text-sm leading-6 text-brand-primary/50">{concept.uncertain}</p></div></div><Link href={concept.lesson} className="mt-6 inline-flex items-center gap-2 text-xs font-bold text-brand-secondary">Open full lesson <ArrowRight size={13}/></Link></article>)}</div></section>

    <section className="mt-24" aria-labelledby="sources-heading"><div className="mb-8"><p className="clinical-label text-brand-emerald-900">Reviewed evidence</p><h2 id="sources-heading" className="newsreader-display mt-3 text-4xl sm:text-5xl">Science with traceable limits</h2></div><div className="overflow-hidden rounded-2xl border border-brand-primary/10">{reviewedScience.map((source)=><a key={source.id} href={source.href} target={source.href.startsWith('http')?'_blank':undefined} rel="noreferrer" className="grid gap-3 border-b border-brand-primary/10 bg-brand-stone-100 p-5 last:border-0 hover:bg-brand-primary/[.025] sm:grid-cols-[1fr_auto] sm:items-center"><div><div className="mb-2 flex flex-wrap gap-2"><span className="clinical-label text-brand-secondary">{source.kind}</span><span className="text-[10px] text-brand-primary/30">{source.year}</span></div><h3 className="font-bold">{source.title}</h3><p className="mt-2 text-xs leading-5 text-brand-primary/45">{source.limitation}</p></div><ShieldCheck className="text-brand-emerald-900" size={18}/></a>)}</div></section>
  </main>;
}
