import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowLeft, ArrowRight, BookMarked, CheckCircle2, Clock3, ExternalLink, Info, MapPin, ShieldAlert } from 'lucide-react';
import { notFound } from 'next/navigation';
import { CITATIONS, COURSES, EvidenceLevel, getCitation, getCourse, getCourseLessons, getLesson } from '@/lib/data/education';
import { getKnowledgeSource, getLessonSourceBundle, type ExtractedIdea, type KnowledgeContributor, type KnowledgeSource } from '@/lib/data/knowledgeSources';
import { getCurriculumEnrichments, type CurriculumEnrichmentUnit } from '@/lib/data/curriculumEnrichment';
import { BotanicalSpecimen, EvidenceLadder, MoleculeField, PolicyTimeline } from '@/components/KnowledgeVisuals';

type Props = { params: Promise<{ course: string; lesson: string }> };
export function generateStaticParams() { return COURSES.flatMap((course) => getCourseLessons(course).map((lesson) => ({course:course.slug,lesson:lesson.slug}))); }
export async function generateMetadata({params}:Props):Promise<Metadata>{ const p=await params; const course=getCourse(p.course); const result=course&&getLesson(course,p.lesson); return result?{title:`${result.lesson.title} | Efifya Learn`,description:result.lesson.summary}:{}; }

export default async function LessonPage({params}:Props){
  const p=await params; const course=getCourse(p.course); if(!course) notFound(); const result=getLesson(course,p.lesson); if(!result) notFound();
  const {lesson}=result; const lessons=getCourseLessons(course); const index=lessons.findIndex((item)=>item.slug===lesson.slug); const previous=lessons[index-1]; const next=lessons[index+1];
  const usedCitationIds=[...new Set(lesson.sections.flatMap((section)=>section.citationIds??[]))];
  const enrichments=getCurriculumEnrichments(lesson.slug);
  const sourceBundle=getLessonSourceBundle(lesson.slug);
  const referenceIds=[...new Set([...usedCitationIds,...sourceBundle.sources.map((source)=>source.id),...enrichments.flatMap((unit)=>unit.sourceIds)])];
  return <main className="min-h-screen">
    <div className="mx-auto grid max-w-[1500px] lg:grid-cols-[270px_minmax(0,760px)_250px]">
      <aside className="hidden border-r border-brand-primary/10 px-5 py-10 lg:block"><div className="sticky top-8"><Link href={`/edu/courses/${course.slug}`} className="mb-8 flex items-center gap-2 text-xs font-bold text-brand-primary/45 hover:text-brand-primary"><ArrowLeft size={14}/>{course.shortTitle}</Link><p className="clinical-label mb-5 text-brand-primary/30">Course contents</p><nav className="space-y-6">{course.modules.map((module)=><div key={module.title}><p className="mb-2 text-xs font-bold text-brand-primary/65">{module.title}</p><div className="space-y-1">{module.lessons.map((item)=><Link key={item.slug} href={`/edu/courses/${course.slug}/${item.slug}`} aria-current={item.slug===lesson.slug?'page':undefined} className={`block rounded-lg px-3 py-2.5 text-xs leading-5 ${item.slug===lesson.slug?'bg-brand-emerald-900/10 font-bold text-brand-emerald-900':'text-brand-primary/40 hover:bg-brand-primary/5 hover:text-brand-primary/70'}`}>{item.title}</Link>)}</div></div>)}</nav></div></aside>
      <article className="px-5 py-10 sm:px-10 lg:px-14 lg:py-16">
        <Link href={`/edu/courses/${course.slug}`} className="mb-8 inline-flex items-center gap-2 text-xs font-bold text-brand-primary/45 lg:hidden"><ArrowLeft size={14}/> Course contents</Link>
        <header className="border-b border-brand-primary/10 pb-10"><div className="mb-5 flex flex-wrap items-center gap-3"><span className="clinical-label text-brand-emerald-900">Lesson {index+1} of {lessons.length}</span><span className="flex items-center gap-1 text-xs text-brand-primary/35"><Clock3 size={13}/>{lesson.duration}</span><span className="text-xs text-brand-primary/35">{lesson.sections.length+enrichments.length} teaching units</span></div><h1 className="newsreader-display text-5xl leading-[.98] sm:text-6xl">{lesson.title}</h1><p className="mt-6 text-lg leading-8 text-brand-primary/55">{lesson.summary}</p></header>
        <LessonVisual slug={lesson.slug}/>
        <section className="my-10 rounded-2xl border border-brand-primary/10 bg-brand-stone-100 p-6"><p className="clinical-label mb-4 text-brand-secondary">By the end, you can</p><ul className="grid gap-3 sm:grid-cols-2">{lesson.objectives.map((objective)=><li key={objective} className="flex gap-2 text-sm leading-6 text-brand-primary/65"><CheckCircle2 className="mt-1 shrink-0 text-brand-emerald-900" size={15}/>{objective}</li>)}</ul></section>
        <ProvenancePanel {...sourceBundle}/>
        <div className="space-y-14">{lesson.sections.map((section,sectionIndex)=><section key={section.id} id={section.id} className="scroll-mt-8"><div className="mb-5 flex items-start gap-4"><span className="newsreader-display mt-1 text-xl text-brand-primary/20">{String(sectionIndex+1).padStart(2,'0')}</span><div><h2 className="newsreader-display text-3xl sm:text-4xl">{section.title}</h2>{section.evidence&&<EvidenceBadge level={section.evidence}/>}</div></div><div className="space-y-5 pl-0 text-base leading-8 text-brand-primary/70 sm:pl-10">{section.paragraphs.map((paragraph)=><p key={paragraph}>{paragraph}</p>)}{section.callout&&<Callout {...section.callout}/>} {section.citationIds&&<div className="flex flex-wrap gap-2 pt-1">{section.citationIds.map((id)=>{const citation=getCitation(id);return citation?<a key={id} href="#references" className="rounded-full border border-brand-primary/10 bg-brand-primary/[.03] px-3 py-1.5 text-[11px] font-bold text-brand-primary/50 hover:text-brand-primary">{citation.authors.split(',')[0]} · {citation.year}</a>:null})}</div>}</div></section>)}</div>
        <ExpandedCurriculum units={enrichments} startIndex={lesson.sections.length}/>
        <section className="mt-16 border-t border-brand-primary/10 pt-9"><p className="clinical-label mb-4 text-brand-primary/35">Key terms</p><div className="flex flex-wrap gap-2">{lesson.keyTerms.map((term)=><span key={term} className="rounded-full border border-brand-primary/10 px-3 py-2 text-xs font-bold text-brand-primary/60">{term}</span>)}</div></section>
        <StudyTools objectives={lesson.objectives} sectionTitles={[...lesson.sections.map((section)=>section.title),...enrichments.map((unit)=>unit.title)]}/>
        <section id="references" className="mt-14 scroll-mt-8 border-t border-brand-primary/10 pt-9"><div className="mb-6 flex items-center gap-3"><BookMarked className="text-brand-secondary"/><div><h2 className="newsreader-display text-3xl">Sources & provenance</h2><p className="mt-1 text-xs text-brand-primary/35">Research, expert synthesis, books and Nigerian essays are labelled by source type—not flattened into one evidence tier.</p></div></div><div className="space-y-3">{referenceIds.map((id)=>{const source=getKnowledgeSource(id);const citation=source??CITATIONS.find((item)=>item.id===id);return citation?<a key={id} href={citation.href} target={citation.href.startsWith('http')?'_blank':undefined} rel="noreferrer" className="group block rounded-xl border border-brand-primary/10 p-5 hover:border-brand-secondary/30"><div className="mb-2 flex flex-wrap items-center gap-2"><span className="rounded-full border border-brand-primary/10 px-2 py-1 text-[9px] font-bold uppercase tracking-wider text-brand-primary/40">{citation.kind}</span>{source&&<span className="rounded-full border border-brand-emerald-900/20 bg-brand-emerald-900/[.05] px-2 py-1 text-[9px] font-bold uppercase tracking-wider text-brand-emerald-900">{source.verification}</span>}</div><p className="font-bold leading-6 group-hover:text-brand-secondary">{citation.title} {citation.href.startsWith('http')&&<ExternalLink className="ml-1 inline" size={13}/>}</p><p className="mt-2 text-xs leading-5 text-brand-primary/40">{citation.authors}. {citation.source}, {citation.year}.</p>{source&&<p className="mt-3 text-xs leading-5 text-brand-primary/45"><strong>Limit:</strong> {source.limitation}</p>}</a>:null})}</div><p className="mt-5 text-xs text-brand-primary/35">Content reviewed {lesson.reviewedAt}. Evidence labels describe confidence in a specific claim, not the overall value of cannabis or its source author.</p></section>
        <nav className="mt-14 grid gap-3 border-t border-brand-primary/10 pt-8 sm:grid-cols-2">{previous?<Link href={`/edu/courses/${course.slug}/${previous.slug}`} className="rounded-xl border border-brand-primary/10 p-5 hover:bg-brand-primary/[.03]"><span className="mb-2 flex items-center gap-1 text-[10px] font-bold uppercase tracking-wider text-brand-primary/35"><ArrowLeft size={12}/> Previous</span><strong>{previous.title}</strong></Link>:<div/>}{next?<Link href={`/edu/courses/${course.slug}/${next.slug}`} className="rounded-xl border border-brand-emerald-900/20 bg-brand-emerald-900/[.06] p-5 sm:text-right"><span className="mb-2 flex items-center justify-end gap-1 text-[10px] font-bold uppercase tracking-wider text-brand-emerald-900">Next <ArrowRight size={12}/></span><strong>{next.title}</strong></Link>:<Link href={`/edu/courses/${course.slug}`} className="rounded-xl border border-brand-emerald-900/20 bg-brand-emerald-900/[.06] p-5 sm:text-right"><span className="text-[10px] font-bold uppercase tracking-wider text-brand-emerald-900">Course complete</span><strong className="mt-2 block">Return to overview</strong></Link>}</nav>
      </article>
      <aside className="hidden border-l border-brand-primary/10 px-5 py-10 xl:block"><div className="sticky top-8"><p className="clinical-label mb-4 text-brand-primary/30">On this page</p><nav className="space-y-2"><a href="#source-synthesis" className="block border-l border-brand-primary/10 py-1 pl-3 text-xs text-brand-primary/40 hover:text-brand-primary">Source synthesis</a>{lesson.sections.map((section)=><a key={section.id} href={`#${section.id}`} className="block border-l border-brand-primary/10 py-1 pl-3 text-xs leading-5 text-brand-primary/40 hover:border-brand-emerald-900 hover:text-brand-primary">{section.title}</a>)}{enrichments.map((unit)=><a key={unit.id} href={`#${unit.id}`} className="block border-l border-sky-300/20 py-1 pl-3 text-xs leading-5 text-brand-primary/40 hover:border-sky-300 hover:text-brand-primary">{unit.title}</a>)}<a href="#references" className="block border-l border-brand-primary/10 py-1 pl-3 text-xs text-brand-primary/40 hover:text-brand-primary">Sources & provenance</a></nav><div className="mt-9 rounded-xl bg-brand-primary/[.03] p-4"><p className="text-xs font-bold">Editorial standard</p><p className="mt-2 text-xs leading-5 text-brand-primary/40">Claims are scoped to the source and reviewed for recency, study design, limitations and conflicts.</p></div></div></aside>
    </div>
  </main>;
}

const evidenceStyles:Record<EvidenceLevel,string>={established:'text-brand-emerald-900 border-brand-emerald-900/25 bg-brand-emerald-900/[.06]',supported:'text-brand-secondary border-brand-secondary/25 bg-brand-secondary/[.06]',preliminary:'text-sky-300 border-sky-300/20 bg-sky-300/[.05]',inconclusive:'text-brand-primary/55 border-brand-primary/15 bg-brand-primary/[.03]'};
function EvidenceBadge({level}:{level:EvidenceLevel}){return <span className={`mt-3 inline-flex rounded-full border px-3 py-1 text-[10px] font-bold uppercase tracking-wider ${evidenceStyles[level]}`}>{level} evidence</span>}
function Callout({title,body,tone}:{title:string;body:string;tone:'note'|'safety'|'nigeria'}){const config={note:{icon:<Info size={18}/>,style:'border-brand-emerald-900/25 bg-brand-emerald-900/[.06] text-brand-emerald-900'},safety:{icon:<ShieldAlert size={18}/>,style:'border-orange-300/25 bg-orange-300/[.06] text-orange-300'},nigeria:{icon:<MapPin size={18}/>,style:'border-brand-secondary/25 bg-brand-secondary/[.06] text-brand-secondary'}}[tone];return <aside className={`my-7 rounded-xl border p-5 ${config.style}`}><div className="flex items-center gap-2 font-bold">{config.icon}{title}</div><p className="mt-2 text-sm leading-6 text-brand-primary/65">{body}</p></aside>}
function LessonVisual({slug}:{slug:string}){
  if(slug==='plant-anatomy') return <figure className="my-10 grid overflow-hidden rounded-2xl border border-brand-emerald-900/20 bg-brand-emerald-900/[.05] sm:grid-cols-[1fr_220px]"><figcaption className="p-6 sm:p-8"><p className="clinical-label text-brand-emerald-900">Visual field note</p><h2 className="newsreader-display mt-3 text-3xl">Structure supports function</h2><p className="mt-3 text-sm leading-6 text-brand-primary/50">Follow the central stem through nodes, branches, leaves and reproductive structures. The drawing is schematic: real morphology varies across development, genotype and environment.</p></figcaption><BotanicalSpecimen className="h-64 w-full text-brand-emerald-900 sm:h-full"/></figure>;
  if(slug==='how-to-read-cannabis-research') return <figure className="my-10 rounded-2xl border border-brand-primary/10 bg-brand-stone-100 p-6 sm:p-8"><figcaption className="mb-6"><p className="clinical-label text-brand-secondary">Evidence hierarchy</p><p className="mt-2 text-sm text-brand-primary/45">Higher synthesis does not remove the need to inspect methods, relevance and bias.</p></figcaption><EvidenceLadder className="max-w-xl text-brand-emerald-900"/></figure>;
  if(slug==='cannabinoids-and-the-ecs'||slug==='dose-route-and-duration'||slug==='terpenes-flavonoids-and-entourage') return <figure className="relative my-10 min-h-64 overflow-hidden rounded-2xl border border-brand-secondary/15 bg-brand-secondary/[.04] p-6"><figcaption className="relative z-10 max-w-sm"><p className="clinical-label text-brand-secondary">Systems view</p><h2 className="newsreader-display mt-3 text-3xl">Compound, route, body, response</h2><p className="mt-3 text-sm leading-6 text-brand-primary/45">Effects emerge from interacting variables—not a compound name alone.</p></figcaption><MoleculeField className="absolute bottom-0 right-0 w-[70%] text-brand-secondary opacity-60"/></figure>;
  if(slug==='cannabinoid-hyperemesis-syndrome') return <figure className="my-10 rounded-2xl border border-orange-300/20 bg-orange-300/[.04] p-6 sm:p-8"><figcaption><p className="clinical-label text-orange-300">Clinical pattern—not a self-test</p><h2 className="newsreader-display mt-3 text-3xl">Exposure → recurrent symptoms → assessment → recovery</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-brand-primary/45">The pattern can raise suspicion, but clinicians must exclude other causes. Sustained cessation helps test and treat the diagnosis.</p></figcaption><div className="mt-7 grid gap-2 sm:grid-cols-4">{['Prolonged exposure','Nausea / vomiting','Medical assessment','Cessation / recovery'].map((step,index)=><div key={step} className="relative rounded-xl border border-brand-primary/10 bg-brand-stone-100 p-4 text-xs font-bold text-brand-primary/60"><span className="mb-6 block text-orange-300">0{index+1}</span>{step}</div>)}</div></figure>;
  if(slug.includes('nigerian')||slug.includes('policy')) return <figure className="my-10 rounded-2xl border border-sky-300/15 bg-sky-300/[.03] p-6 sm:p-8"><figcaption className="mb-8"><p className="clinical-label text-sky-300">Legal context</p><p className="mt-2 text-sm text-brand-primary/45">A timeline gives orientation; current status still requires the controlling text and amendments.</p></figcaption><PolicyTimeline/></figure>;
  return null;
}
function StudyTools({objectives,sectionTitles}:{objectives:string[];sectionTitles:string[]}){return <section className="mt-14 grid gap-4 border-t border-brand-primary/10 pt-9 sm:grid-cols-2"><div className="rounded-2xl border border-brand-emerald-900/20 bg-brand-emerald-900/[.05] p-6"><p className="clinical-label text-brand-emerald-900">Lesson synthesis</p><h2 className="newsreader-display mt-3 text-3xl">Connect the ideas</h2><ul className="mt-5 space-y-3">{sectionTitles.map((title,index)=><li key={title} className="flex gap-3 text-sm leading-6 text-brand-primary/55"><span className="newsreader-display text-brand-emerald-900">{String(index+1).padStart(2,'0')}</span>{title}</li>)}</ul></div><div className="rounded-2xl border border-brand-secondary/20 bg-brand-secondary/[.04] p-6"><p className="clinical-label text-brand-secondary">Check your understanding</p><h2 className="newsreader-display mt-3 text-3xl">Can you explain it?</h2><ol className="mt-5 space-y-4">{objectives.map((objective,index)=><li key={objective} className="text-sm leading-6 text-brand-primary/55"><strong className="mr-2 text-brand-secondary">{index+1}.</strong>{objective}—without relying on a slogan?</li>)}</ol><p className="mt-6 border-t border-brand-primary/10 pt-4 text-xs leading-5 text-brand-primary/35">If an answer changes a health or legal decision, return to the cited section and inspect the source before acting.</p></div></section>}

function ProvenancePanel({sources,ideas,contributors}:{sources:KnowledgeSource[];ideas:ExtractedIdea[];contributors:KnowledgeContributor[]}){
  const classes=new Set(sources.map((source)=>source.kind));
  return <section id="source-synthesis" className="my-12 scroll-mt-8 overflow-hidden rounded-2xl border border-sky-300/15 bg-sky-300/[.025]"><div className="grid gap-5 border-b border-brand-primary/10 p-6 sm:grid-cols-[1fr_auto] sm:items-end"><div><p className="clinical-label text-sky-300">Curriculum provenance</p><h2 className="newsreader-display mt-3 text-3xl">How this lesson was assembled</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-brand-primary/50">Extracted ideas connect the source library to lesson claims. Each source keeps its evidence class, limitations and verification status.</p></div><div className="flex gap-5 text-center"><div><strong className="newsreader-display block text-2xl">{sources.length}</strong><span className="text-[9px] font-bold uppercase tracking-wider text-brand-primary/35">sources</span></div><div><strong className="newsreader-display block text-2xl">{classes.size}</strong><span className="text-[9px] font-bold uppercase tracking-wider text-brand-primary/35">source types</span></div></div></div>{ideas.length>0&&<div className="grid md:grid-cols-2">{ideas.map((idea)=><article key={idea.id} className="border-b border-brand-primary/10 p-6 last:border-0 md:odd:border-r md:[&:nth-last-child(-n+2)]:border-b-0"><div className="mb-3 flex items-center gap-2"><EvidenceBadge level={idea.evidence}/></div><h3 className="font-bold">{idea.title}</h3><p className="mt-3 text-sm leading-6 text-brand-primary/55">{idea.synthesis}</p><div className="mt-4 flex flex-wrap gap-2">{idea.sourceIds.map((id)=>{const source=getKnowledgeSource(id);return source?<a key={id} href="#references" className="rounded-full border border-brand-primary/10 px-2.5 py-1 text-[10px] font-bold text-brand-primary/40 hover:text-brand-secondary">{source.authors.split(',')[0]} · {source.year}</a>:null})}</div></article>)}</div>}{contributors.length>0&&<div className="border-t border-brand-primary/10 p-6"><p className="clinical-label mb-4 text-brand-primary/30">Researcher lenses represented</p><div className="flex flex-wrap gap-2">{contributors.map((contributor)=><a key={contributor.id} href={contributor.profileHref} target="_blank" rel="noreferrer" className="rounded-full border border-brand-primary/10 bg-brand-stone-100 px-3 py-2 text-xs font-bold text-brand-primary/55 hover:text-brand-secondary">{contributor.name} · {contributor.expertise[0]}</a>)}</div></div>}</section>;
}

function ExpandedCurriculum({units,startIndex}:{units:CurriculumEnrichmentUnit[];startIndex:number}){
  if(units.length===0) return null;
  return <section className="mt-16 border-t border-brand-primary/10 pt-10"><div className="mb-12 rounded-2xl border border-sky-300/15 bg-sky-300/[.03] p-6 sm:p-8"><p className="clinical-label text-sky-300">Source-derived curriculum</p><h2 className="newsreader-display mt-3 text-4xl">Extended study</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-brand-primary/50">These units turn the merged research library, researcher perspectives, MedGriot essays and books into teaching content and applied practice.</p></div><div className="space-y-16">{units.map((unit,index)=><article key={unit.id} id={unit.id} className="scroll-mt-8"><div className="mb-6 flex items-start gap-4"><span className="newsreader-display mt-1 text-xl text-sky-300/40">{String(startIndex+index+1).padStart(2,'0')}</span><div><p className="clinical-label mb-2 text-sky-300">Extended unit</p><h2 className="newsreader-display text-3xl sm:text-4xl">{unit.title}</h2><EvidenceBadge level={unit.evidence}/></div></div><div className="space-y-5 text-base leading-8 text-brand-primary/70 sm:pl-10"><p className="text-lg font-medium leading-8 text-brand-primary/80">{unit.lede}</p>{unit.paragraphs.map((paragraph)=><p key={paragraph}>{paragraph}</p>)}<aside className="my-7 rounded-xl border border-brand-secondary/20 bg-brand-secondary/[.05] p-5"><p className="clinical-label text-brand-secondary">{unit.activity.label}</p><p className="mt-3 text-sm font-medium leading-6 text-brand-primary/70">{unit.activity.prompt}</p></aside><div className="flex flex-wrap gap-2 pt-1">{unit.sourceIds.map((id)=>{const source=getKnowledgeSource(id);return source?<a key={id} href="#references" className="rounded-full border border-sky-300/15 bg-sky-300/[.03] px-3 py-1.5 text-[11px] font-bold text-brand-primary/50 hover:text-sky-300">{source.authors.split(',')[0]} · {source.year} · {source.kind}</a>:null})}</div></div></article>)}</div></section>;
}
