const VISUALS:Record<string,{label:string;title:string;caption:string;steps:string[]}>={
  'what-is-cannabis':{label:'Classification map',title:'One material, four questions',caption:'A useful label depends on the decision being made.',steps:['Botany: structure','Chemistry: composition','Law: definition','Health: product + exposure']},
  'cannabinoids-and-the-ecs':{label:'ECS network',title:'Signal × receptor × tissue × time',caption:'The endocannabinoid system is a distributed regulatory network, not a single on/off switch.',steps:['Endocannabinoids','CB1 + CB2','Enzymes + targets','Body response']},
  'terpenes-flavonoids-and-entourage':{label:'Entourage map',title:'Compound × ratio × route × person',caption:'Cannabis constituents can modify one another through several testable mechanisms.',steps:['Cannabinoids','Terpenes + flavonoids','Metabolism + receptors','Lived response']},
  'medical-evidence':{label:'Evidence matrix',title:'Goal × product × outcome × person',caption:'Trials, lived experience and comparative care illuminate different parts of therapeutic use.',steps:['Intended benefit','Defined product','Meaningful outcome','Fit + trade-offs']},
  'synthetic-cannabinoids':{label:'Uncertainty pathway',title:'Street name ≠ chemical identity',caption:'When identity is unknown, symptoms and emergency response matter more than guessing.',steps:['Unverified name','Unknown mixture','Unpredictable exposure','Treat the emergency']},
  'dependence-tolerance-and-withdrawal':{label:'Change framework',title:'Function before frequency',caption:'Assessment connects exposure to control, consequences and support.',steps:['Pattern of use','Control + function','Withdrawal + risk','Support + review']},
  'pregnancy-youth-and-vulnerability':{label:'Risk model',title:'Exposure meets vulnerability',caption:'Risk is modified by developmental stage, health history and interacting exposures.',steps:['Product + dose','Age or pregnancy','Health history','Precaution + care']},
  'how-to-read-nigerian-cannabis-law':{label:'Legal hierarchy',title:'Verify before acting',caption:'Commentary can explain law but cannot replace the current controlling text.',steps:['Current statute','Amendments + cases','Agency practice','Essay or headline']},
  'policy-models-and-public-health':{label:'Policy system',title:'A label contains many design choices',caption:'Outcomes depend on the complete regulatory bundle and local capacity.',steps:['Legal model','Market rules','Health safeguards','Equity + evaluation']},
  'environment-and-plant-development':{label:'Systems botany',title:'Genotype × environment × time',caption:'Observed traits emerge from interacting variables, not a single strain label.',steps:['Inherited potential','Environment','Development','Measured phenotype']},
  'quality-contaminants-and-testing':{label:'Certificate audit',title:'Sample → method → result → scope',caption:'A report is only as relevant as the sample and measurements it documents.',steps:['Batch identity','Validated method','Units + limits','Claim boundary']},
  'harvest-drying-curing-and-stability':{label:'Hazard pathway',title:'Post-harvest change continues',caption:'Water, temperature, oxygen, light and time shape stability and microbial risk.',steps:['Harvest state','Drying conditions','Packaging','Storage + retest']},
  'cannabis-across-cultures':{label:'Historical method',title:'Claim → source → context → corroboration',caption:'Cultural significance and modern clinical efficacy are different questions.',steps:['Historical claim','Source purpose','Power + bias','Corroboration']},
  'stigma-language-and-media':{label:'Frame audit',title:'What is selected—and what disappears?',caption:'Apply the same evidence questions to prohibition, advocacy and promotion.',steps:['Who is speaking?','What is claimed?','What supports it?','What is missing?']},
  'cannabis-in-africa-and-nigeria':{label:'Evidence mosaic',title:'No single source tells the whole history',caption:'Archives, oral histories, trade records and law illuminate different parts.',steps:['Movement + trade','Local practice','Colonial control','Modern political economy']},
};

export default function LessonConceptVisual({slug}:{slug:string}){
  const visual=VISUALS[slug];if(!visual)return null;
  return <figure className="my-10 overflow-hidden rounded-2xl border border-brand-primary/10 bg-brand-stone-100"><figcaption className="border-b border-brand-primary/10 p-6 sm:p-8"><p className="clinical-label text-sky-300">{visual.label}</p><h2 className="newsreader-display mt-3 text-3xl">{visual.title}</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-brand-primary/45">{visual.caption}</p></figcaption><div className="grid sm:grid-cols-2 lg:grid-cols-4">{visual.steps.map((step,index)=><div key={step} className="relative border-b border-brand-primary/10 p-5 last:border-0 sm:odd:border-r lg:border-b-0 lg:border-r lg:last:border-r-0"><span className="newsreader-display text-2xl text-sky-300/35">0{index+1}</span><strong className="mt-8 block text-sm leading-5">{step}</strong>{index<visual.steps.length-1&&<span className="absolute right-3 top-1/2 hidden text-brand-primary/20 lg:block">→</span>}</div>)}</div></figure>;
}
